# Generated by Django 4.1.1 on 2022-11-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_address_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Author Info'},
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.ManyToManyField(null=True, to='book_outlet.country'),
        ),
    ]
